version: 1.6.0.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
test:
  # only assemblies to test
  assemblies:
    only:
      - OAuth.Net.Tests.dll

configuration: Release
before_build:
- cmd: dotnet restore
build_script:
- cmd: build.cmd Release
artifacts:
- path: '**\*.nupkg'
after_test:
- choco install opencover.portable
- choco install dotnetcore-sdk
- choco install codecov
- OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -oldstyle -targetargs:"test -c Release test\OAuth.Net.Tests.csproj" -output:oauth.xml
- codecov -f "oauth.xml"